FROM python

WORKDIR /app

COPY . /app

CMD ["python", "rng.py"]


# docker build .
# docker run <image>

# docker -it <container>

# Terminal açmakta zorunda değiliz. Interaktif tek kullanımlıkta kullanılabilir.
# Bu uygulamada input isteniyor bu sebeple interaktif yapı çalışıyor.
# docker -i <container>