apiVersion: v1
kind: Service
metadata:
  name: application-load-balancer
spec:
  selector:
    balance: opened-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
    - protocol: TCP
      port: 8000
      targetPort: 8000
    - protocol: TCP
      port: 80
      targetPort: 80