apiVersion: apps/v1
kind: Deployment 
metadata:
  name: auth-deployment
spec:
  selector:
    matchLabels:
      app: auth-app
  template:
    metadata:
      labels:
        app: auth-app
    spec:
      containers:
        - name: auth-app
          image: huseyin/kub-demo-auth:latest