apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  labels:
    balance: opened-service
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80