apiVersion: apps/v1
kind: Deployment 
metadata:
  name: task-deployment
spec:
  selector:
    matchLabels:
      app: task-app
  template:
    metadata:
      labels:
        app: task-app
    spec:
      containers:
        - name: task-app
          image: huseyin/kube-demo-task:latest
          resources:
            limits:
              memory: 500Mi
              cpu: 500Mi
          env:
            - name: AUTH_ADDRESS
              value: "auth-service.default"
            - name: TASK_FORDER
              value: tasks