apiVersion: v1 
kind: Service
metadata:
  name: task-service
  labels:
    balance: opened-service
spec:
  selector:
    app: task-app
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000