apiVersion: v1
kind: Service
metadata:
  name: users-service
  labels:
    balance: opened-service
spec:
  selector:
    app: users-app
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  